import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  // ==================== COMMON ====================
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },

  // ==================== HOME SCREEN ====================
  searchContainer: {
    padding: 15,
    backgroundColor: '#fff',
    flexDirection: 'row',
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
    fontSize: 16,
  },
  searchButton: {
    backgroundColor: '#DC0A2D',
    paddingHorizontal: 20,
    justifyContent: 'center',
    borderRadius: 8,
    minWidth: 50,
  },
  searchButtonText: {
    fontSize: 20,
    textAlign: 'center',
  },
  errorContainer: {
    backgroundColor: '#ffebee',
    padding: 15,
    margin: 15,
    borderRadius: 8,
  },
  errorText: {
    color: '#c62828',
    textAlign: 'center',
    fontSize: 14,
    marginBottom: 10,
  },
  retryButton: {
    backgroundColor: '#DC0A2D',
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  retryButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#FFF',
  },
  listContainer: {
    padding: 10,
    paddingBottom: 20,
  },
  pokemonCard: {
    flex: 1,
    backgroundColor: '#fff',
    margin: 5,
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  pokemonImage: {
    width: 100,
    height: 100,
  },
  pokemonName: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 5,
    textAlign: 'center',
    color: '#333',
  },

  loadMoreText: {
  color: '#fff',
  fontWeight: 'bold',
  fontSize: 16,
},
loadingOverlay: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0, 0, 0, 0.6)',
  justifyContent: 'center',
  alignItems: 'center',
  zIndex: 1000,
},
  pokemonNumber: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  floatingButton: {
  position: 'absolute',
  bottom: 40,
  right: 40,
  width: 60,
  height: 60,
  borderRadius: 30,
  backgroundColor: '#DC0A2D',
  justifyContent: 'center',
  alignItems: 'center',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.3,
  shadowRadius: 5,
  elevation: 8,
  zIndex: 999,
},
floatingButtonText: {
  fontSize: 28,
},
  loadMoreButton: {
    backgroundColor: '#DC0A2D',
    padding: 15,
    margin: 15,
    borderRadius: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  loadMoreText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },

  // ==================== DETAILS SCREEN ====================
  detailsContainer: {
    padding: 20,
  },
  detailsHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  detailsImage: {
    width: 200,
    height: 200,
  },
  favoriteButton: {
    backgroundColor: '#fff',
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#DC0A2D',
    marginTop: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  favoriteButtonActive: {
    backgroundColor: '#DC0A2D',
  },
  favoriteButtonText: {
    color: '#DC0A2D',
    fontWeight: 'bold',
    fontSize: 16,
  },
  favoriteButtonTextActive: {
    color: '#fff',
  },
  detailsName: {
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#333',
  },
  detailsNumber: {
    fontSize: 18,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
  },
  typesContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 30,
    flexWrap: 'wrap',
  },
  typeBadge: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  typeText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  statsContainer: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    color: '#333',
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  statName: {
    width: 100,
    fontSize: 11,
    fontWeight: 'bold',
    color: '#666',
  },
  statBarContainer: {
    flex: 1,
    height: 8,
    backgroundColor: '#e0e0e0',
    borderRadius: 4,
    marginHorizontal: 10,
    overflow: 'hidden',
  },
  statBar: {
    height: '100%',
    backgroundColor: '#DC0A2D',
    borderRadius: 4,
  },
  statValue: {
    width: 40,
    textAlign: 'right',
    fontWeight: 'bold',
    color: '#333',
    fontSize: 14,
  },
  abilitiesContainer: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  abilityItem: {
    paddingVertical: 8,
  },
  abilityText: {
    fontSize: 16,
    color: '#333',
    textTransform: 'capitalize',
  },

  // ==================== FAVORITES SCREEN ====================
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  emptyText: {
    fontSize: 64,
    marginBottom: 10,
  },
  emptySubtext: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
  },
  favoritesListContainer: {
    padding: 15,
  },
  favoriteCard: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    padding: 15,
    marginBottom: 10,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  favoriteImage: {
    width: 80,
    height: 80,
  },
  favoriteInfo: {
    flex: 1,
    marginLeft: 15,
  },
  favoriteName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  favoriteNumber: {
    fontSize: 14,
    color: '#666',
    marginTop: 5,
  },
  clearButtonContainer: {
  padding: 16,
  paddingBottom: 8,
},
clearButton: {
  backgroundColor: '#FF6B6B',
  padding: 12,
  borderRadius: 8,
  alignItems: 'center',
},
clearButtonText: {
  color: '#fff',
  fontSize: 16,
  fontWeight: '600',
},
});


export default styles;